title: HP Wireless Printer | Install HP Driver
description: Get the simple steps of the Hp printer setup through 123.hp.com/Setup. Download the driver and install it on your device. Enjoy high quality pictures and printing.
